// =========================
// CENTRALIZED PRODUCT DATA
// =========================

const PRODUCTS = [
  {
    id: 0,
    badge: "Best Seller",
    image: "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?auto=format&fit=crop&w=800&q=80",
    imageAlt: "Canon EOS R5",
    category: "Mirrorless Full-frame",
    name: "Canon EOS R5",
    brand: "Canon",
    rating: "★★★★★",
    reviews: 128,
    price: "150.000.000 VNĐ",
    priceRaw: 150000000,
    oldPriceRaw: 175000000,
    stock: 15,
    description: "Quay 8K, lấy nét siêu nhanh, chuẩn cho nhiếp ảnh chuyên nghiệp. Canon EOS R5 là chiếc máy ảnh mirrorless hàng đầu với khả năng quay video 8K RAW cùng cảm biến 45MP full-frame thế hệ mới.",
    specs: [
      "Cảm biến Full-frame 45MP CMOS",
      "Quay video 8K RAW 24fps",
      "Lấy nét siêu nhanh DPAF II (0.05s)",
      "ISO native 100-51,200",
      "Chống rung IBIS 8 bậc",
      "Kết nối Wi-Fi 6 & Bluetooth 5.0"
    ],
    isHero: true,
    heroSubtitle: "Ưu đãi đặc biệt giảm đến 15%",
    heroDesc: "Chuyên nghiệp 4K, khung hình siêu nhanh - Exclusive cho KNG Store",
    heroBg: "linear-gradient(rgba(10, 14, 39, 0.4), rgba(10, 14, 39, 0.5)), url('https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=1920&q=80')"
  },
  {
    id: 1,
    badge: "Hot",
    image: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=800&q=80",
    imageAlt: "Sony A7R IV",
    category: "Mirrorless 61MP",
    name: "Sony A7R IV",
    brand: "Sony",
    rating: "★★★★★",
    reviews: 95,
    price: "120.000.000 VNĐ",
    priceRaw: 120000000,
    oldPriceRaw: 145000000,
    stock: 8,
    description: "Độ phân giải cực cao, hoàn hảo cho studio và nhiếp ảnh thương mại. Sony A7R IV với cảm biến 61MP cho ảnh cực kỳ chi tiết, phù hợp cho in ấn khổ lớn và chụp ảnh phong cảnh.",
    specs: [
      "Cảm biến 61MP Full-frame BSI CMOS",
      "AF 425 điểm pha lấy nét",
      "Quay 4K 30fps Super 35",
      "Độ phân giải cực cao — in khổ cực lớn",
      "Real-time Eye AF & Animal AF",
      "Thân máy chống bụi/nước chuẩn IPX4"
    ],
    isHero: true,
    heroSubtitle: "Khuyến mãi siêu phẩm - Giảm 18%",
    heroDesc: "Sensor Full Frame 61MP, AI Focus - Giới hạn 50 chiếc",
    heroBg: "linear-gradient(rgba(10, 14, 39, 0.4), rgba(10, 14, 39, 0.5)), url('https://images.unsplash.com/photo-1510127034890-ba27508e9f1c?auto=format&fit=crop&w=1920&q=80')"
  },
  {
    id: 2,
    badge: "New",
    image: "https://images.unsplash.com/photo-1512790182412-b19e6d62bc39?auto=format&fit=crop&w=800&q=80",
    imageAlt: "Nikon Z9",
    category: "Pro Mirrorless",
    name: "Nikon Z9",
    brand: "Nikon",
    rating: "★★★★★",
    reviews: 42,
    price: "140.000.000 VNĐ",
    priceRaw: 140000000,
    oldPriceRaw: 155000000,
    stock: 5,
    description: "Flagship mạnh mẽ nhất từ Nikon không có màn trập cơ, chuyên nghiệp video 8K, tối ưu cho content creator và thể thao.",
    specs: [
      "Cảm biến 45.7MP Stacked CMOS",
      "Không màn trập cơ, màn trập điện tử hoàn toàn",
      "Quay 8K 60p & 4K 120p",
      "Chụp liên tục 120fps (11MP)",
      "AF nhận diện 9 loại đối tượng",
      "Màn hình cảm ứng nghiêng 4 trục"
    ],
    isHero: true,
    heroSubtitle: "Bộ sưu tập bán hàng - Giảm 20%",
    heroDesc: "Chuyên nghiệp video 8K, tối ưu cho content creator",
    heroBg: "linear-gradient(rgba(10, 14, 39, 0.4), rgba(10, 14, 39, 0.5)), url('nikon_z9_banner.png')"
  },
  {
    id: 3,
    badge: "Retro",
    image: "https://images.unsplash.com/photo-1510127034890-ba27508e9f1c?auto=format&fit=crop&w=800&q=80",
    imageAlt: "Fujifilm X-T5",
    category: "APS-C Creative",
    name: "Fujifilm X-T5",
    brand: "Fujifilm",
    rating: "★★★★★",
    reviews: 210,
    price: "45.000.000 VNĐ",
    priceRaw: 45000000,
    oldPriceRaw: 50000000,
    stock: 20,
    description: "Thiết kế cổ điển, màu film đẹp. Fujifilm X-T5 nổi bật với cảm biến 40MP độ phân giải siêu cao và khả năng giả lập màu phim xuất sắc.",
    specs: [
      "Cảm biến 40MP X-Trans CMOS 5 HR",
      "19 mô phỏng màu Film Fujifilm",
      "Quay video 6.2K 30p",
      "Thiết kế retro, dial cơ học",
      "IBIS 7.0 bậc bù rung",
      "Gọn nhẹ, lấy nét thông minh"
    ],
    isHero: true,
    heroSubtitle: "Flash Sale cuối tháng - Giảm 16%",
    heroDesc: "Retro Design + 40MP, X-Trans Sensor - Bảo hành 3 năm",
    heroBg: "linear-gradient(rgba(10, 14, 39, 0.4), rgba(10, 14, 39, 0.5)), url('https://images.unsplash.com/photo-1516724562728-afc824a36e84?auto=format&fit=crop&w=1920&q=80')"
  },
  {
    id: 4,
    badge: "Hybrid",
    image: "https://images.unsplash.com/photo-1512790182412-b19e6d62bc39?auto=format&fit=crop&w=800&q=80",
    imageAlt: "Nikon Z6 II",
    category: "Hybrid Camera",
    name: "Nikon Z6 II",
    brand: "Nikon",
    rating: "★★★★☆",
    reviews: 67,
    price: "80.000.000 VNĐ",
    priceRaw: 80000000,
    oldPriceRaw: null,
    stock: 12,
    description: "Hiệu năng cân bằng cho cả quay phim và chụp ảnh chuyên sâu. Nikon Z6 II là lựa chọn hybrid hoàn hảo với bộ xử lý kép EXPEED 6.",
    specs: [
      "Cảm biến 24.5MP Full-frame BSI CMOS",
      "Hybrid AF 273 điểm pha",
      "Quay 4K 60fps & ProRes RAW",
      "Chụp liên tục 14fps với AF",
      "Bộ xử lý kép EXPEED 6",
      "Khe cắm kép UHS-II & CFexpress"
    ],
    isHero: false
  },
  {
    id: 5,
    badge: "Pro DSLR",
    image: "https://images.unsplash.com/photo-1516724562728-afc824a36e84?auto=format&fit=crop&w=800&q=80",
    imageAlt: "Canon EOS 5D Mark IV",
    category: "DSLR Full-frame",
    name: "Canon EOS 5D Mark IV",
    brand: "Canon",
    rating: "★★★★★",
    reviews: 340,
    price: "90.000.000 VNĐ",
    priceRaw: 90000000,
    oldPriceRaw: null,
    stock: 2,
    description: "Biểu tượng DSLR bền bỉ cho chụp cưới, sự kiện và studio. Canon EOS 5D Mark IV là chuẩn mực DSLR chuyên nghiệp.",
    specs: [
      "Cảm biến 30.4MP Full-frame CMOS",
      "AF 61 điểm — 41 cross-type",
      "Quay 4K 30fps / Full HD 120fps",
      "Thân máy chống bụi/nước cao cấp",
      "GPS & Wi-Fi tích hợp",
      "Khe nhớ kép CF + SD"
    ],
    isHero: false
  },
  {
    id: 6,
    badge: "Sports",
    image: "https://images.unsplash.com/photo-1520390138845-fd2d229dd553?auto=format&fit=crop&w=800&q=80",
    imageAlt: "Sony A9 II",
    category: "Speed Performance",
    name: "Sony A9 II",
    brand: "Sony",
    rating: "★★★★★",
    reviews: 55,
    price: "110.000.000 VNĐ",
    priceRaw: 110000000,
    oldPriceRaw: 125000000,
    stock: 0, // Out of stock for testing
    description: "Tốc độ chụp siêu nhanh cho thể thao, sự kiện và báo chí. Sony A9 II với tốc độ chụp 20fps silent, không bị blackout.",
    specs: [
      "Cảm biến 24.2MP Full-frame Stacked CMOS",
      "AF 693 điểm lấy nét siêu tốc",
      "Chụp 20fps liên tục, không blackout",
      "Quay 4K 60fps video chuyên nghiệp",
      "LAN port cho truyền ảnh tốc độ cao",
      "Real-time Eye AF & Bird AF"
    ],
    isHero: false
  }
];
